config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  #
  
  get '/about', to: 'about#index'
  get '/cv', to: 'cv#index'

  resources :guides

  get '/search', to: 'search#index'

  resources :users, only: [:show] do
    resources :guides, only: [:index], module: :users
  end

  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  post '/logout', to: 'sessions#destroy'

  get '/contacts', to: 'contacts#new', as: 'contact'

  # Defines the root path route ("/")
  root 'guides#index'

end

app/models/guide.rb
class Guide < ApplicationRecord
  # Relationships
  belongs_to :creator, class_name: 'User'

  # Validations
  validates :title, presence: true
  validates :description, presence: true
end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController
  skip_before_action :require_login, only: [:index, :show]

  def index

    @search_text = params[:search]
    guides = Guide.where(is_draft: false).includes(:creator).order(created_at: :desc)

    if params[:search] != nil && !params[:search].empty?
      puts 'if' *10
      @guides = guides
        .where("title ILIKE ?", "%" + params[:search] + "%")
        .or(guides.where("description ILIKE ?", "%" + params[:search] + "%"))
        .or(guides.where("body ILIKE ?", "%" + params[:search] + "%")).order(created_at: :desc)
    else
      @guides = guides
    end
  end

  def show
    unless logged_in?
      @guide = Guide.where(is_draft: false).and(Guide.where(id: params[:id])).first
    else
      @guide = Guide.where(id: params[:id]).first
    end
    ## find users name for displaying author
    ## if statement is only to prevent error when search results return articles you are not allowd to see, rm when fixed
    unless @guide
      flash[:alert] = "Not allowed to view article" 
      redirect_back_or_to guides_path 
    end
    #if @guide
    #  user = User.find_by(id: @guide.creator_id)
    #  @username = user.name
    #end
  end

  def new
    if logged_in? && current_user[:id]
      @guide = Guide.new
    else
      flash[:alert] = "Not allowed to write articles" 
      redirect_back_or_to guides_path 
    end
  end

  def create
    if logged_in? && current_user[:id]
      ## Using helper method "current_user"
      ## Not sure if I will use helper or collect data from session directry.
      current_user_id = session[:user_id]
      current_user = User.find_by_id(current_user_id)
      if guide_params[:is_draft] == '1'
        guide_params[:is_draft] = true
      else
        guide_params[:is_draft] = false
      end
      if guide_params[:free_for_all] == '1'
        guide_params[:free_for_all] = true
      else
        guide_params[:free_for_all] = false
      end
      @guide = Guide.new(guide_params)
      @guide.creator = current_user

      if @guide.save
        redirect_to @guide
      else
        render :new, status: :unprocessable_entity
      end

    else
      flash[:alert] = "Not allowed to create articles" 
      redirect_back_or_to guides_path 
    end
  end

  def edit
    if logged_in? && current_user[:id]
      guide = Guide.find(params[:id])
      if guide.creator_id == current_user[:id]
        @guide = guide
      end
    else

      flash[:alert] = "Not allowed to edit articles" 
      redirect_back_or_to guides_path 
    end
  end

  def update
    if logged_in? && current_user[:id]
      @guide = Guide.find(params[:id])

      if @guide.update(guide_params)
        redirect_to @guide
      else
        render :edit, status: :unprocessable_entity
      end
    else
      flash[:alert] = "Not allowed to update this article"
      redirect_back_or_to guides_path
    end
  end

  def destroy
    if logged_in? && current_user[:id]
      @guide = Guide.find(params[:id])
      user = @guide.creator.id
      if @guide.destroy
        redirect_to({controller: 'users', action: 'show', id: user})
      end
    else
      flash[:alert] = "Not allowed to delete article"
    end
  end

  private

  def guide_params
    params.require(:guide).permit(:title, :description, :introduction, :body, :free_for_all, :is_draft)
  end
end

app/controllers/users/guides_controller.rb
module Users
  class GuidesController < ApplicationController
  include ApplicationHelper
  
    def index

      puts '#' * 1000
      puts params
      @search_text = params[:search]
      if logged_in? && current_user[:id]
        current_user_id = current_user[:id]
        if current_user_id == params[:user_id].to_i
          puts 'if"""""""""""""""""""'
          guides = Guide.where(creator_id: params[:user_id]).includes(:creator)
        else
          puts 'else###############################'
          guides = Guide.where(creator_id: params[:user_id]).includes(:creator).and(Guide.where(is_draft: false))
        end
        
        if params[:search] != nil && !params[:search].empty?
          @guides = guides
            .where("title ILIKE ?", "%" + params[:search] + "%")
            .or(guides.where("description ILIKE ?", "%" + params[:search] + "%"))
            .or(guides.where("body ILIKE ?", "%" + params[:search] + "%")).includes(:creator)
        else
          @guides = guides
        end
      else
        flash[:alert] = "Not authorized"
        redirect_back_or_to guides_path
      end
    end
  end
end

app/views/guides/_form.html.erb
<%= form_with model: @guide do | form | %> 
  <div>
    <%= form.label :title, class: "label has-text-white" %>
    <br>
    <%= form.text_field :title, class: "input", placeholder: "Title" %>
      <% @guide.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>

  <div>
    <%= form.label :description, class: "label has-text-white mt-3" %>
    <br>
    <%= form.text_area :description, class: "textarea", placeholder: "Article..." %>
      <% @guide.errors.full_messages_for(:description).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>

  <div>
    <%= form.label :introduction, class: "label has-text-white mt-3" %>
    <br>
    <%= form.text_area :introduction, class: "textarea", placeholder: "Article..." %>
      <% @guide.errors.full_messages_for(:introduction).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>
  <div>
    <%= form.label :body, class: "label has-text-white mt-3" %>
    <br>
    <%= form.text_area :body, class: "textarea", :autofocus => true, placeholder: "Article..." %>
      <% @guide.errors.full_messages_for(:body).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>
  <!--
  <div>
    <%= form.file_field :picture %>
    </div>
  -->
  <div>
    <%= form.label :is_draft, "Save as draft" %>
    <%= form.check_box :is_draft %>
  </div>
  <div>
    <%= form.submit class: "button is-success mt-2" %>
  </div>
<% end %>

app/views/guides/dummy-create.html.erb
<section class="section">
  <div class="container">
    <h1 class="title has-text-white text-is-centered">
      create
    </h1>
      <% form_with model: @Article do | form | %> 
    <div>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </div>

    <div>
      <%= form.label :body %><br>
      <%= form.text_area :body %>
    </div>

    <div>
      <%= form.submit %>
    </div>
  </div>
</section>

app/views/guides/edit.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% if logged_in? && @guide %>
        <div class="column is-half is-offset-one-quarter ">
          <h1 class="title has-text-white text-is-centered">
            Edit article
          </h1>
          <%= render "form", guide: @guide %>
        </div>
      <% else %>
        <%= render "errors/not_allow_to_create" %>
      <% end %>
    </div>
  </div>
</section>

app/views/guides/index.html.erb
<%= render "application/guides" %>

app/views/guides/new.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <div class="column is-half is-offset-one-quarter ">
        <h1 class="title has-text-white text-is-centered">
          Write article
        </h1>
        <%= render "form", guide: @guide %>
      </div>
    </div>
  </div>
</section>

app/views/guides/show.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <div class="column is-three-fifths is-offset-one-fifth">
        <% if @guide %>
          <h1 class="title is-1 has-text-centered has-text-white"><%= @guide.title %></h1>
          <p class="has-text-centered has-text-white is-size-7"> Published <%= @guide.created_at %></p>
          </br>
          <p class="has-text-centered has-text-white"><%= @guide.title %></p>
          </br>
          <p class="has-text-centere has-text-white"><%= @guide.introduction %></p>
          <hr class=solid">
          <p class="has-text-centere has-text-white"><%= @guide.body.html_safe %></p>
          </br>
          <div class="buttons mt-2">
            <%= link_to "Back", :back, class: "button is-info" %>
          
            <% if logged_in? && current_user[:id] == @guide.creator_id %>
                <%= link_to "Edit", edit_guide_path(@guide), class: "button is-warning" %>
                <%= button_to "Delete", @guide, method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "button is-warning" %>
            <% end %>
          </div>
        <% else %>
          <h1>No article available</h1>
          <%= link_to "Back", :guides, class: "button is-info" %>
        <% end %>
      </div>
    </div>
  </div>
</section>